AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AI File Processor - Process files in S3 using Claude Bedrock'

Parameters:
  StackPrefix:
    Type: String
    Description: 'Prefix for the stack resources'
  ModelId:
    Type: String
    Description: 'The Bedrock model ID to use for processing files'
  BedrockRoleArn:
    Type: String
    Description: 'ARN of the IAM role for Bedrock batch processing'

Globals:
  Function:
    Timeout: 900  # 15 minutes (maximum for Lambda)
    Runtime: python3.11
    MemorySize: 1024
    Environment:
      Variables:
        STACK_PREFIX: !Ref StackPrefix

Resources:
  TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${StackPrefix}-ai-processor-trigger'
      CodeUri: src/trigger/
      Handler: handler.lambda_handler
      Description: Triggered when prompt.json is uploaded
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucket
          MODEL_ID: !Ref ModelId
          BEDROCK_ROLE_ARN: !GetAtt BedrockBatchRole.Arn
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub '${StackPrefix}-ai-file-processor-input'
        - S3WritePolicy:
            BucketName: !Ref OutputBucket
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:ListFoundationModels
              - bedrock:GetFoundationModel
              - bedrock:ListInferenceProfiles
              - bedrock:GetInferenceProfile
              - bedrock:ListCustomModels
              - bedrock:GetCustomModel
              - bedrock:TagResource 
              - bedrock:UntagResource 
              - bedrock:ListTagsForResource
              - bedrock:GetModelInvocationJob
              - bedrock:ListModelInvocationJobs  
              - bedrock:StopModelInvocationJob
            Resource: "*"
          - Effect: Allow
            Action:
              - bedrock:CreateModelInvocationJob
            Resource: 
              - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:foundation-model/${ModelId}'
              - !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:model-invocation-job/*"
              
  TriggerFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TriggerFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${StackPrefix}-ai-file-processor-input'
  InputBucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${StackPrefix}-ai-file-processor-input'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt TriggerFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: prompt.json
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DependsOn: TriggerFunctionPermission  
  OutputBucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${StackPrefix}-ai-file-processor-output'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  BedrockBatchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${StackPrefix}-bedrock-batch-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockBatchS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${InputBucket}/*"
                  - !Sub "${OutputBucket}/*"
                  - !Ref InputBucket
                  - !Ref OutputBucket
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: "*"

        

